site_name: MetaPepView Documentation
site_url: https://RamonZwaan.github.io/metapepview/

plugins:
  - search
  - roamlinks

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
extra_css:
  - stylesheets/extra.css
  
theme:
  name: material

nav:
  - Introduction: index.md
  - Installation: installation.md
  - Getting started: getting-started.md
  - Prepare input data: prepare-input-data.md
  - User guide:
    - Data management: 
      - Data import: data-import.md
      - Annotation: annotation.md
      - Project table: project-table.md
    - Community visualization:
      - Overview: community-visualization.md
      - Community composition: taxonomy-visualization.md
      - Community function: function-visualization.md
    - Experiment evaluation:
      - Overview: experiment-performances-biases.md
      - Spectral evaluation: experiment-evaluation.md
      - Build reference dataset: build-reference-dataset.md
      - Evaluate community composition: evaluate-taxonomy.md
  - MetaPepView backend:
    - Annotation pipeline: annotation-pipeline.md
#    - Spectral processing: spectra-processing.md
#    - Quantification taxa/functions: quantification.md

